import matplotlib.pyplot as plt
from autosteper.plotter import FullereneDataParser_Plotter
from autosteper.tools import strip_extraFullerene


a_plotter = FullereneDataParser_Plotter()
a_plotter.plot_pathway_unit(src_pathway_root=r'path_rank_1', # this is the lowest-energy pathway generated by AutoSteper for #4169 C66Cl10
                            new_pathway_workbase=r'./',
                            group_symbol='Cl',
                            proj_ring_seq=[61, 62, 63, 64, 65, 66])
